// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tests.proxies;

public class EmptyEntity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emptyEntityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Tests.EmptyEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Dummy("Dummy"),
		EmptyEntity_Order("Tests.EmptyEntity_Order");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmptyEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Tests.EmptyEntity"));
	}

	protected EmptyEntity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emptyEntityMendixObject)
	{
		if (emptyEntityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Tests.EmptyEntity", emptyEntityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Tests.EmptyEntity");

		this.emptyEntityMendixObject = emptyEntityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmptyEntity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static tests.proxies.EmptyEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return tests.proxies.EmptyEntity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static tests.proxies.EmptyEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tests.proxies.EmptyEntity(context, mendixObject);
	}

	public static tests.proxies.EmptyEntity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tests.proxies.EmptyEntity.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Dummy
	 */
	public final java.lang.String getDummy()
	{
		return getDummy(getContext());
	}

	/**
	 * @param context
	 * @return value of Dummy
	 */
	public final java.lang.String getDummy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dummy.toString());
	}

	/**
	 * Set value of Dummy
	 * @param dummy
	 */
	public final void setDummy(java.lang.String dummy)
	{
		setDummy(getContext(), dummy);
	}

	/**
	 * Set value of Dummy
	 * @param context
	 * @param dummy
	 */
	public final void setDummy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dummy)
	{
		getMendixObject().setValue(context, MemberNames.Dummy.toString(), dummy);
	}

	/**
	 * @return value of EmptyEntity_Order
	 */
	public final tests.proxies.Order getEmptyEntity_Order() throws com.mendix.core.CoreException
	{
		return getEmptyEntity_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of EmptyEntity_Order
	 */
	public final tests.proxies.Order getEmptyEntity_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		tests.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmptyEntity_Order.toString());
		if (identifier != null)
			result = tests.proxies.Order.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EmptyEntity_Order
	 * @param emptyentity_order
	 */
	public final void setEmptyEntity_Order(tests.proxies.Order emptyentity_order)
	{
		setEmptyEntity_Order(getContext(), emptyentity_order);
	}

	/**
	 * Set value of EmptyEntity_Order
	 * @param context
	 * @param emptyentity_order
	 */
	public final void setEmptyEntity_Order(com.mendix.systemwideinterfaces.core.IContext context, tests.proxies.Order emptyentity_order)
	{
		if (emptyentity_order == null)
			getMendixObject().setValue(context, MemberNames.EmptyEntity_Order.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EmptyEntity_Order.toString(), emptyentity_order.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emptyEntityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tests.proxies.EmptyEntity that = (tests.proxies.EmptyEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Tests.EmptyEntity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
